name: collabrenomics
favicon: null
layout_spectrum: 0.1431146482937038
typography_spectrum: 0.5392614684533328
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9127645308617502
  lightness: 0.03526147082448006
  saturation: 0.7690060746390373
  rhythmicContrast: 0.029074693098664284
purpose: []
